lab5: Mitchell_Lab5.o OpenHashTable.o Timer.o ClosedHashTable.o
	g++ Mitchell_Lab5.o OpenHashTable.o Timer.o ClosedHashTable.o -o lab5
Mitchell_Lab5.o: Mitchell_Lab5.cpp
	g++ -c Mitchell_Lab5.cpp
OpenHashTable.o: OpenHashTable.cpp
	g++ -c OpenHashTable.cpp
Timer.o: Timer.cpp
	g++ -c Timer.cpp
ClosedHashTabl.o: ClosedHashTable.cpp
	g++ -c ClosedHashTable.cpp
clean:
	rm -f *o *~ lab*
